* as per brlcad's request -- not my usual style  ;-)
git-svn-id: https://bzflag.svn.sourceforge.net/svnroot/bzflag/branches/trepan@18431 08b3d480-bf2c-0410-a26f-811ee3361c24

diff --git a/misc/touchcopyright b/misc/touchcopyright
--- a/misc/touchcopyright
+++ b/misc/touchcopyright
@@ -1,31 +1,48 @@
 #!/bin/sh
-# BZFlaga
-# NOTE: update all three lines below
-# Copyright (c) 1993 - 2001 Tim Riker
-OLDCOPYRIGHTTEXT='Copyright (c) 1993 - 2001'
-NEWCOPYRIGHTTEXT='Copyright (c) 1993 - 2001'
+# BZFlag
+# Copyright (c) 1993 - 2008 Tim Riker
+OLDCOPYRIGHTTEXT='Copyright (c) 1993 - 2007'
+# NOTE: update just this line and then run the script
+NEWCOPYRIGHTTEXT='Copyright (c) 1993 - 2008'
 #
 # update copyright in all files
 #
+# bzflag top-level dir
+for root in . .. ; do
+  if [ -r $root/bzflag.lsm.in ] ; then
+    break
+  fi
+done
 
-# top-level dir
-root=".."
-
-if [ -r ../bin/bzfs ] ; then
- echo "$0 should be run only after a make pristine!"
- exit 1
-fi 
-
-rm -f updatecopyright.tmp
-files=`find $root -type f | grep -v updatecopyright`
+#if [ -r $root/include/config.h ] ; then
+#  echo "$0 should be run only after a make maintainer-clean!"
+#  exit 1
+#fi
+myname=touchcopyright
+tmpfile=$root/$myname.tmp
+rm -f $tmpfile
+# touch myself last
+files="`find $root -type f -not -regex '.*\.svn.*' -not -regex '.*src/other.*' | grep -v 'png$' | grep -v misc/$myname` misc/$myname"
 
 # do replacement
 for file in $files; do
- if [ ! -w ${file} ]; then
-  echo "${file} not found or not writable."
-  continue
- fi
- sed -e "s/${OLDCOPYRIGHTTEXT}/${NEWCOPYRIGHTTEXT}/" < ${file} > updatecopyright.tmp
- mv updatecopyright.tmp ${file}
+  echo -e -n "$file\r"
+  if [ ! -w ${file} ]; then
+    echo "${file} not found or not writable."
+    continue
+  fi
+  # cat to the file, not move to preserve permissions
+  if sed -e "s/${OLDCOPYRIGHTTEXT}/${NEWCOPYRIGHTTEXT}/" < ${file} > $tmpfile ; then
+    cat $tmpfile > ${file}
+  fi
 done
-rm -f updatecopyright.tmp
+rm -f $tmpfile
+
+# Local Variables: ***
+# mode:sh ***
+# tab-width: 8 ***
+# sh-indentation: 2 ***
+# sh-basic-offset: 2 ***
+# indent-tabs-mode: t ***
+# End: ***
+# ex: shiftwidth=2 tabstop=8
